### ISSUE TITLE
Consider dropping Python 2 support

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [vetleledaal/game-engine-finder#18]
Is it OK if we drop Python 2 support? I have a bugfix patch that requires Python 3.5+, and I'd prefer not to rewrite it to support ancient EOL Python versions that haven't gotten security patches in years.

**Comment by vetleledaal** [comment]
Python 2 support was mostly added because it wasn't much of a hindrance to support. I have no reservations with dropping it now since it's EOL, and actually causing issues.
