### ISSUE TITLE
Cocos2d support

### ISSUE THREAD

**Issue by Faalagorn** [vetleledaal/game-engine-finder#3]
Seems Cocos2d games could be detected by presence of the .dll files at least, figured it out after seeing that Metal Slug 3 have libcocos2d.dll and libCocosDenshion.dll. it probably needs testing on more than one game though.

**Comment by vetleledaal** [comment]
Figuring out the version would also be preferable. Other games using this engine should also be checked for similarities: https://www.pcgamingwiki.com/wiki/Engine:Cocos2d . I don't have time to address this at the moment, but I'll have some free time to delve into this in about a month.

**Comment by vetleledaal** [comment]
Not exactly a month later, but support for Cocos2d has been added in this commit https://github.com/vetleledaal/game-engine-finder/commit/f788f9614327bf1d3d0a75cc0c0a12ed8549685c .

it's a bit hacky, but the alternative of reading the assembly might introduce addition dependencies, specifically for handling PE images. I made some notes here https://pastebin.com/g6V9dXSD . In any case, the current solution works for the 3 games I've tested (Finding Teddy, Badland, Metal Slug 3)
