### ISSUE TITLE
Why restricting this to game engines?

### ISSUE THREAD

**Issue by mirh** [vetleledaal/game-engine-finder#9]
From bink and physx versions, to DRM analysis akin to protectionid.

**Comment by vetleledaal** [comment]
This project was just intended to be a quick hack to get the engine a game uses. To account for other information, like the middleware table, it would at least require some work for this flow, probably another script, preferably sharing common code with the existing script.

I've tried to automatically detect middleware in the past, but this lead to a lot of false positives, specifically leftover .dll files that were not loaded by the game at all. So to detect this properly you might have to look at the imported modules for the game.

-- That said, with all the work required to turn this hacky script to a proper know-it-all protectionid clone I would rather start over with a better architecture suited for this.

**Comment by mirh** [comment]
Mhh, I don't know. 
It's true that you can't just blindly grep binaries for the first string that comes to your mind (steam mass effect exe has "dead code" securom mention for example).. And thank you for pointing out that a dll being present doesn't equal being loaded and used. 

OTOH checking the .exe for the actual functions and then the dll for version would already seem fairly solid. 
Also, a python script is exactly how I would have pictured something so casual but at the same time editor-y. 

But you are the boss.

**Comment by mirh** [comment]
Actually, even imports are fairly meaningless. I just checked [CoDWaWmp](https://github.com/kcat/dsoal/issues/157#issuecomment-3447776850) and despite the fact that it loads dsound (on top of the fact that binkw32 should too) its api is XAudio2 which is loaded through *CoCreateInstance* and doesn't appear there.
Paradoxically though, I feel like searching [CLSIDs](https://github.com/evilrat666/directx-d/blob/master/src/directx/xaudio2.d) (byte swapped like `483FC2FAF531A845B49B5225D61401AA` or `3FCC0139B584A44FBA35AA8172B8A09B` for DirectSound8) has very little chance of false positives.

Also another very stupid simple information that could be noted, is whether any file in the folder is above 4 GiB.

**Comment by vetleledaal** [comment]
The [YARA rules](https://redirect.github.com/mirkobrombin/Bottles/blob/3fe4825ece4c40e2d425119db2c5570a8269ee86/bottles/backend/managers/eagle.yar) from Bottles' [Eagle](https://usebottles.com/eagle) feature might be of interest.
